api/urls.py
from django.conf.urls import url, include
from rest_framework.schemas import get_schema_view
from rest_framework_simplejwt.views import (
    TokenObtainPairView, TokenRefreshView)
from rest_framework import views, serializers, status
from rest_framework.response import Response
from api.views import ImeiList, upload_imei_data


class MessageSerializer(serializers.Serializer):
    message = serializers.CharField()


class EchoView(views.APIView):
    def post(self, request, *args, **kwargs):
        serializer = MessageSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        return Response(serializer.data, status=status.HTTP_201_CREATED)

urlpatterns = [
    url(r'^$', get_schema_view()),
    url(r'^upload/$', upload_imei_data),
    url(r'^auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^auth/token/obtain/$', TokenObtainPairView.as_view()),
    url(r'^auth/token/refresh/$', TokenRefreshView.as_view()),
    url(r'^echo/$', EchoView.as_view()),
    url(r'^imei-v1/$', ImeiList.as_view(), name='api-imei-list'),
]

backend/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views
from log.forms import LoginForm  # Importando Formulario de Login

# Estas URL son para loguear, luego se pasa a las url de la app log
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('log.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^login/$', views.login, {'template_name': 'login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', views.logout, {'next_page': '/login'}),
]

jerarquia/urls.py
from django.conf.urls import url, include
from jerarquia import views



urlpatterns = [
    url(r'^jerarquia/$', views.jerarquia, name='jerarquia'),
    url(r'^editar/(?P<codigo_unico>\w+)/$', views.consulta_codigo, name='consulta'),
    url(r'^aprobar/', views.aprobar, name='aprobar'),
    url(r'^aprobar_cambio/(?P<codigo_unico>\w+)/$', views.consulta_cambio, name='aprobar_cambio'),
    url(r'^cerrar/$', views.cerrar_jerarquia, name='cerrar'),
    url(r'^descarga_especial/$', views.descarga_especial, name='descarga_especial'),
    url(r'^descarga_jerarquia/$', views.descarga_jerarquia, name='descarga_jerarquia'),
    url(r'^formulario_aprobador/$', views.formularios_vista_aprobador, name='vista_aprobador'),
    url(r'^nuevo_agente/$', views.nuevo_agente, name='agregar_agente'),]

jerarquia/models.py
from django.db import models
from django.contrib.auth.models import User

class Tipo(models.Model):
	tipo=models.CharField(max_length=5)
	ldap = models.ForeignKey(User, null=True)
	def __str__(self):
		return self.tipo

class TipoAa(models.Model):
	tipo_aa=models.CharField(max_length=100)
	ldap = models.ForeignKey(User, null=True)
	def __str__(self):
		return self.tipo_aa

class Oficina(models.Model):
	oficina=models.CharField(max_length=25)
	ldap = models.ForeignKey(User, null=True)
	def __str__(self):
		return self.oficina

class Rif(models.Model):
	rif=models.CharField(max_length=10)
	ldap = models.ForeignKey(User, null=True)
	def __str__(self):
		return self.rif

class CodigoDeudor(models.Model):
	codigo_deudor=models.CharField(max_length=10)
	ldap = models.ForeignKey(User, null=True)
	def __str__(self):
		return self.codigo_deudor

class Nombre(models.Model):
	nombre=models.CharField(max_length=100)
	ldap = models.ForeignKey(User, null=True)
	def __str__(self):
		return self.nombre

class Direccion(models.Model):
	direccion=models.CharField(max_length=1000)
	ldap = models.ForeignKey(User, null=True)
	def __str__(self):
		return self.direccion

class Region(models.Model):
	region=models.CharField(max_length=25)
	ldap = models.ForeignKey(User, null=True)
	def __str__(self):
		return self.region

class Gerente(models.Model):
	gerente=models.CharField(max_length=50)
	ldap = models.ForeignKey(User, null=True)
	def __str__(self):
		return self.gerente

class Lider(models.Model):
	lider=models.CharField(max_length=50)
	ldap = models.ForeignKey(User, null=True)
	def __str__(self):
		return self.lider

class Coordinador(models.Model):
	coordinador=models.CharField(max_length=50)
	ldap = models.ForeignKey(User, null=True)
	def __str__(self):
		return self.coordinador


class CentroRecarga(models.Model):
	centro_recarga=models.CharField(max_length=50)
	ldap = models.ForeignKey(User, null=True)
	def __str__(self):
		return self.centro_recarga


class Distribuidor(models.Model):
	distribuidor=models.CharField(max_length=200)
	ldap = models.ForeignKey(User, null=True)
	def __str__(self):
		return self.distribuidor


class Status(models.Model):
	status=models.CharField(max_length=200)
	ldap = models.ForeignKey(User, null=True)
	def __str__(self):
		return self.status


class Estados(models.Model):
    id_estado = models.AutoField(primary_key=True)
    estado = models.CharField(max_length=250)
    def __str__(self):
        return self.estado


class Ciudades(models.Model):
    id_ciudad = models.AutoField(primary_key=True)
    id_estado = models.ForeignKey(Estados, db_column='id_estado')
    ciudad = models.CharField(max_length=200)
    capital = models.SmallIntegerField()
    def __str__(self):
        return str(self.ciudad, self.capital)

class Municipios(models.Model):
    id_municipio = models.AutoField(primary_key=True)
    id_estado = models.ForeignKey(Estados, db_column='id_estado')
    municipio = models.CharField(max_length=100)
    def __str__(self):
        return str(self.municipio)

class Parroquias(models.Model):
    id_parroquia = models.AutoField(primary_key=True)
    id_municipio = models.ForeignKey(Municipios, db_column='id_municipio')
    parroquia = models.CharField(max_length=250)
    def __str__(self):
        return self.parroquia


class Historico(models.Model):
	a000sap = models.CharField(max_length=25,null=True)
	codigo_unico = models.CharField(max_length=25,null=True)
	visitas = models.IntegerField(null=True)
	latitud = models.FloatField(null=True)
	longitud = models.FloatField(null=True)
	direccion_fisica = models.CharField(max_length=2000,null=True)
	direccion_fiscal = models.CharField(max_length=2000,null=True)
	persona_contacto = models.CharField(max_length=70,null=True)
	correo_tienda = models.CharField(max_length=70,null=True)
	correo_empresario = models.CharField(max_length=70,null=True)
	telefono_empresario = models.CharField(max_length=20,null=True)
	telefono_tienda = models.CharField(max_length=20,null=True)
	hora_apertura = models.TimeField(null=True)
	hora_cierre = models.TimeField(null=True)
	empleados = models.IntegerField(null=True)
	punto_rojo = models.BooleanField()
	caso_remedy = models.CharField(max_length=25,null=True)
	# sustitucion = models.CharField(max_length=25,null=True)
	fecha = models.DateField(null=True)
	enero = models.BooleanField(default=False)
	febrero = models.BooleanField(default=False)
	marzo = models.BooleanField(default=False)
	abril = models.BooleanField(default=False)
	mayo = models.BooleanField(default=False)
	junio = models.BooleanField(default=False)
	julio = models.BooleanField(default=False)
	agosto = models.BooleanField(default=False)
	septiembre = models.BooleanField(default=False)
	octubre = models.BooleanField(default=False)
	noviembre = models.BooleanField(default=False)
	diciembre = models.BooleanField(default=False)
	municipio_key = models.ForeignKey(Municipios, on_delete=models.CASCADE,null=True)
	estado_key = models.ForeignKey(Estados, on_delete=models.CASCADE,null=True)
	tipo_key = models.ForeignKey(Tipo,on_delete=models.CASCADE,null=True)
	tipo_aa_key = models.ForeignKey(TipoAa,on_delete=models.CASCADE,null=True)
	oficina_key = models.ForeignKey(Oficina,on_delete=models.CASCADE,null=True)
	codigo_deudor_key = models.ForeignKey(CodigoDeudor,on_delete=models.CASCADE,null=True)
	nombre_key = models.ForeignKey(Nombre,on_delete=models.CASCADE,null=True)
	direccion_key = models.ForeignKey(Direccion,on_delete=models.CASCADE,null=True)
	region_key = models.ForeignKey(Region,on_delete=models.CASCADE,null=True)
	coordinador_key = models.ForeignKey(Coordinador,on_delete=models.CASCADE,null=True)
	lider_key = models.ForeignKey(Lider,on_delete=models.CASCADE,null=True)
	gerente_key = models.ForeignKey(Gerente,on_delete=models.CASCADE,null=True)
	centro_recarga_key = models.ForeignKey(CentroRecarga,on_delete=models.CASCADE,null=True)
	distribuidor_key = models.ForeignKey(Distribuidor,on_delete=models.CASCADE,null=True)
	status_key = models.ForeignKey(Status,on_delete=models.CASCADE,null=True)
	rif_key  = models.ForeignKey(Rif,on_delete=models.CASCADE,null=True)
	def __str__(self):
		return str(self.codigo_unico)

class Temporal(models.Model):
	a000sap = models.CharField(max_length=25,null=True)
	codigo_unico = models.CharField(max_length=25,null=True)
	visitas = models.IntegerField(null=True)
	latitud = models.CharField(max_length=20,null=True)
	longitud = models.CharField(max_length=20,null=True)
	direccion_fisica = models.CharField(max_length=2000,null=True)
	direccion_fiscal = models.CharField(max_length=2000,null=True)
	estado_key = models.ForeignKey(Estados, on_delete=models.CASCADE,null=True)
	municipio_key = models.ForeignKey(Municipios, on_delete=models.CASCADE,null=True)
	persona_contacto = models.CharField(max_length=70,null=True)
	correo_tienda = models.CharField(max_length=70,null=True)
	correo_empresario = models.CharField(max_length=70,null=True)
	telefono_empresario = models.CharField(max_length=20,null=True)
	telefono_tienda = models.CharField(max_length=20,null=True)
	hora_apertura = models.TimeField(null=True)
	hora_cierre = models.TimeField(null=True)
	empleados = models.IntegerField(null=True)
	punto_rojo = models.BooleanField(default=False)
	caso_remedy = models.CharField(max_length=25,null=True,blank=True)
	# sustitucion = models.CharField(max_length=25,null=True,blank=True)
	enero = models.BooleanField(default=False)
	febrero = models.BooleanField(default=False)
	marzo = models.BooleanField(default=False)
	abril = models.BooleanField(default=False)
	mayo = models.BooleanField(default=False)
	junio = models.BooleanField(default=False)
	julio = models.BooleanField(default=False)
	agosto = models.BooleanField(default=False)
	septiembre = models.BooleanField(default=False)
	octubre = models.BooleanField(default=False)
	noviembre = models.BooleanField(default=False)
	diciembre = models.BooleanField(default=False)
	tipo_key = models.ForeignKey(Tipo,on_delete=models.CASCADE,null=True)
	tipo_aa_key = models.ForeignKey(TipoAa,on_delete=models.CASCADE,null=True)
	oficina_key = models.ForeignKey(Oficina,on_delete=models.CASCADE,null=True)
	codigo_deudor_key = models.ForeignKey(CodigoDeudor,on_delete=models.CASCADE,null=True)
	nombre_key = models.ForeignKey(Nombre,on_delete=models.CASCADE,null=True)
	direccion_key = models.ForeignKey(Direccion,on_delete=models.CASCADE,null=True)
	region_key = models.ForeignKey(Region,on_delete=models.CASCADE,null=True)
	coordinador_key = models.ForeignKey(Coordinador,on_delete=models.CASCADE,null=True)
	lider_key = models.ForeignKey(Lider,on_delete=models.CASCADE,null=True)
	gerente_key = models.ForeignKey(Gerente,on_delete=models.CASCADE,null=True)
	centro_recarga_key = models.ForeignKey(CentroRecarga,on_delete=models.CASCADE,null=True,blank=True)
	distribuidor_key = models.ForeignKey(Distribuidor,on_delete=models.CASCADE,null=True,blank=True)
	status_key = models.ForeignKey(Status,on_delete=models.CASCADE,null=True)
	rif_key = models.ForeignKey(Rif,on_delete=models.CASCADE,null=True)
	ldap = models.ForeignKey(User, null=True)
	def __str__(self):
		return str(self.codigo_unico)

class Cambio(models.Model):
	a000sap = models.CharField(max_length=25)
	codigo_unico = models.CharField(max_length=25)
	visitas = models.IntegerField()
	latitud = models.FloatField()
	longitud = models.FloatField()
	direccion_fisica = models.CharField(max_length=2000)
	direccion_fiscal = models.CharField(max_length=2000)
	estado_key = models.ForeignKey(Estados, on_delete=models.CASCADE,null=True)
	municipio_key = models.ForeignKey(Municipios, on_delete=models.CASCADE,null=True)
	persona_contacto = models.CharField(max_length=70)
	correo_tienda = models.CharField(max_length=70)
	correo_empresario = models.CharField(max_length=70)
	telefono_empresario = models.CharField(max_length=20)
	telefono_tienda = models.CharField(max_length=20)
	hora_apertura = models.TimeField()
	hora_cierre = models.TimeField()

jerarquia/templates/jerarquia.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<form method="POST" action="{%url 'jerarquia'%}" id="consulta">{% csrf_token %}
<div class = "row">
<div class="col-xs-3">
<h4>Tipo</h4>
{{filtro.tipo}}
</div>

<div class="col-xs-3">
<h4>Lider</h4>
{{filtro.lider}}
</div>
<div class="col-xs-3">
<h4>Codigo</h4>
{{filtro.codigo}}
</div>
</div>
</form>
{{consulta}}
<div class ="box top-buffer">
	<div class="box-body">
<div class="col-xs-12" id="data_table" name="data_table">
	<table id="results" name="results" class="table">
		<thead>
			<tr>
			<th scope="col">Codigo Unico</th>
			<th scope="col">Nombre</th>
			<th scope="col">Lider</th>
			<th scope="col">Editar</th>
			</tr>

		</thead>

		<tbody>

		</tbody>
	</table>
</div>
</div>
</div>
<div id="popup" class="modal fade" role="dialog">
</div>



{% endblock %}
{% block extra_js %}
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.quicksearch/2.4.0/jquery.quicksearch.min.js"></script>
<script>
$(document).ready(function() {
    $(function() {
        $('#id_lider,#id_tipo,#id_region,#id_codigo').change(function() {
					var tipo = $("#id_tipo").val();
					var region = $("#id_region").val();
					var lider = $("#id_lider").val();
					dropdown(tipo,region,lider);
          consulta();

        });
    });

		function dropdown(tipo,region,lider){

		}

    function consulta() {

        $.ajax({
            url: $("#consulta").attr('action'),
            type: $("#consulta").attr('method'),
            data: $("#consulta").serialize(),
            success: function(data) {
              var str = '';
              jQuery.each(data, function(key, value) {
                var route = "'/editar/"+value['codigo']+"/'"
                str += '<tr><td>' + value['codigo'] + '</td>' +
                        '<td>' + value['nombre'] + '</td>' +
                        '<td>' + value['lider'] + '</td>' +
                        '<td>'+'<a onclick="return abrir_modal('+route+')" class="btn btn-info"><span class="glyphicon glyphicon-edit"></span></a>'+
                        '</td></tr>'
                });
            $('table[name=results] thead').html('		<tr><th scope="col">Codigo Unico</th><th scope="col">Nombre</th><th scope="col">Lider</th><th scope="col">Editar</th></tr>')
            $('table[name=results] tbody').html(str)
      	    .hide()
            .fadeIn(1500, function() { $('#results'); });
            }

        })

    }

});

</script>

<script>
function abrir_modal(url)
{
        $('#popup').load(url, function()
        {
                $(this).modal('show');
        });
        return false;
};
function cerrar_modal()
{
        $('#popup').modal('hide');
        return false;
};
</script>

<script>
$(document).ready(function() {
  $(window).keydown(function(event){
    if(event.keyCode == 13) {
      event.preventDefault();
      return false;
    }
  });
});
</script>
<script>
$(document).ready(function () {
    $(document).ajaxStart(function () {
        $("#loading").show();
    }).ajaxStop(function () {
        $("#loading").hide();
    });
});
</script>
<style>
.top-buffer { margin-top:40px; }

</style>

{%endblock%}

jerarquia/templates/jerarquia_aprobar.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class ="box top-buffer">
	<div class="box-body">
<div class="col-xs-12" id="data_table" name="data_table">
	<table id="results" name="results" class="table white text-center">
		<thead>
			<td>Codigo Unico</td>
			<td>Nombre</td>
			<td>Lider</td>
			<td>Revisar</td>
		</thead>
		<tbody>
		{% for result in results %}
			<tr>
				<td>{{result.codigo_unico}}</td>
				<td>{{result.nombre_key__nombre}}</td>
				<td>{{result.lider_key__lider}}</td>
        <td><a onclick="return abrir_modal('/aprobar_cambio/{{result.codigo_unico}}/')" class="btn btn-info"><span class="glyphicon glyphicon-search"></span></a>
        </td></tr>

			</tr>
		{% endfor %}
		</tbody>
	</table>
</div>
</div>
</div>
<div id="popup" class="modal fade" role="dialog">
</div>



{% endblock %}
{% block extra_js %}
<script>
function abrir_modal(url)
{
        $('#popup').load(url, function()
        {
                $(this).modal('show');
        });
        return false;
};
function cerrar_modal()
{
        $('#popup').modal('hide');
        return false;
};
</script>
{%endblock%}

jerarquia/templates/jerarquia_descarga.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<form method="POST" enctype="multipart/form-data"> {% csrf_token %}
{{form}}
</form>
{%endblock%}

jerarquia/templates/jerarquia_vista_aprobador.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}


<div class="row">
	<div class="col-md-12">
	{{mensaje|safe}}
						</div>


<div class="col-md-offset-1 col-md-2">

</div>
<div class="col-md-4">
		{%for field in f%}
		<form method="POST">{% csrf_token %}
			<div class="row top-buffer">
		{{field.label_tag}}{{field}}<input type="submit" value="Agregar" name="{{field.name}}" class="btn btn-info">
		</div>
		</form>
		{%endfor%}
</div>


<!-- {%for field in f%}
<form method="POST">{% csrf_token %}
<table>
	<tr>
<th>{{field.label_tag}}</th>
<th>{{field}}</th>
<th><input type="submit" value="Agregar" name="{{field.name}}"></th>
</tr>
</table>
</form>
{%endfor%} -->


</div>
<div id="popup" class="modal fade" role="dialog">
</div>
{%if f%}
<div class="col-md-offset-4 col-md-2 top-buffer-2">
<div class="row ">
<a onclick="return abrir_modal('/nuevo_agente/')" class="btn btn-info">Agregar Nuevo Agente  <span class="glyphicon glyphicon-plus"></span></a>
</div>
</div>

<div class="row top-buffer">
</div>
{%endif%}
{% endblock %}
{% block extra_js %}
<style>

th, td {
    padding: 15px;
    text-align: left;
}

</style>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.quicksearch/2.4.0/jquery.quicksearch.min.js"></script>

<script>
function abrir_modal(url)
{
        $('#popup').load(url, function()
        {
                $(this).modal('show');
        });
        return false;
};
function cerrar_modal()
{
        $('#popup').modal('hide');
        return false;
};
</script>

<script>
$(document).ready(function() {
  $(window).keydown(function(event){
    if(event.keyCode == 13) {
      event.preventDefault();
      return false;
    }
  });
});
</script>
<script>
$(document).ready(function () {
    $(document).ajaxStart(function () {
        $("#loading").show();
    }).ajaxStop(function () {
        $("#loading").hide();
    });
});
</script>
<style>
.top-buffer { margin-top:20px; }
.top-buffer-2 { margin-top:29px; }
</style>


{%endblock%}